// Tipos de usuário
export const USER_TYPES = {
  ADMIN: 'ADMINISTRADOR',
  CLIENT: 'CLIENTE'
};

// Status de denúncia
export const COMPLAINT_STATUS = {
  PENDING: 'PENDENTE',
  ANALYZED: 'ANALISADA',
  REJECTED: 'REJEITADA',
  ACCEPTED: 'ACEITA'
};

// Códigos de erro HTTP
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500
};